language: java
jdk:
  - oraclejdk8

install: true
script:
  - mvn clean install
  - mvn clean test jacoco:report

after_success:
  - bash <(curl -s https://codecov.io/bash) -t f3ecce27-b32a-470c-9ce7-4ecd147f61fc

cache:
  directories:
    - '$HOME/.m2/repository'
